Repository SCarcG1/IIC3141-3-HubUC-Backend, pull requests merged in 2025-06, with the labels that each got.

#38 Endpoints de private lesson (crear, get all y por id)
  app/api/routes.py
  app/crud/private_lesson.py
  app/schemas/private_lesson.py
Labels: feature

#42 Todos los endpoints de course
  app/api/routes.py
  app/crud/course.py
  app/crud/private_lesson.py
  app/schemas/course.py
  requirements.txt
Labels: feature

#46 Feature delete lesson
  app/api/routes.py
  app/crud/private_lesson.py
  app/schemas/private_lesson.py
Labels: feature

#80 fix(tests): agregada la dependecia de description para tests
  app/models/private_lesson.py
  app/models/reservation.py
  app/models/review.py
Labels: bug

#88 test(reservation): agrega pruebas unitarias para mejorar cobertura de…
  app/api/routes.py
  app/crud/private_lesson.py
  app/schemas/private_lesson.py
  tests/test_private_lesson_crud.py
  tests/test_private_lesson_endpoints.py
  tests/test_reservation_crud.py
  tests/test_reservation_endpoints.py
Labels: chore

#116 feat(reservation): impedir crear reservaciones para lecciones privadas cerradas
  alembic/env.py
  app/api/private_lessons.py
  app/api/routes.py
  app/crud/private_lesson.py
  app/crud/reservation.py
  app/crud/user.py
  app/database.py
  app/models/private_lesson.py
  app/schemas/private_lesson.py
  app/schemas/reservation.py
  requirements.txt
  tests/api/test_private_lesson_endpoints.py
  tests/api/test_reservation_endpoints.py
  tests/crud/test_private_lesson_crud.py
  tests/crud/test_reservation_crud.py
  tests/db_for_tests.py
Labels: deuda técnica

#117 Feature(review): endpoints review y campo extra
  app/api/reviews.py
  app/crud/reservation.py
  app/crud/review.py
  app/main.py
  app/models/review.py
  app/schemas/review.py
  tests/api/test_reservation_endpoints.py
  tests/api/test_review_endpoints.py
Labels: deuda técnica
